"""changed id

Revision ID: 15a89653558c
Revises: 5da09548f1f7
Create Date: 2022-05-18 00:12:12.306732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a89653558c'
down_revision = '5da09548f1f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
