"""autogenerate files table

Revision ID: 31286dbaf3f8
Revises: 57db7f402df0
Create Date: 2022-05-17 18:30:25.767991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31286dbaf3f8'
down_revision = '57db7f402df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
