"""fixed dance creator missing field

Revision ID: 3997d5444eec
Revises: d9993d05ecb9
Create Date: 2022-05-18 23:34:07.678270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3997d5444eec'
down_revision = 'd9993d05ecb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.add_column('dances', sa.Column('creator_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'dances', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dances', type_='foreignkey')
    op.drop_column('dances', 'creator_id')
    op.create_table('files',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='files_pkey'),
    sa.UniqueConstraint('filename', name='files_filename_key')
    )
    # ### end Alembic commands ###
