"""fixed some author song fields

Revision ID: 45d7ae45c60d
Revises: 15a89653558c
Create Date: 2022-05-18 16:32:08.304590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d7ae45c60d'
down_revision = '15a89653558c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
