"""added UUID to files table

Revision ID: ba8e44803972
Revises: 31286dbaf3f8
Create Date: 2022-05-17 18:31:11.495954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8e44803972'
down_revision = '31286dbaf3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
