"""changed file logic

Revision ID: d9993d05ecb9
Revises: 8fd2278f8830
Create Date: 2022-05-18 20:04:11.293575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9993d05ecb9'
down_revision = '8fd2278f8830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dances', sa.Column('filename', sa.String(), nullable=False))
    op.drop_constraint('dances_file_id_fkey', 'dances', type_='foreignkey')
    op.drop_column('dances', 'file_id')
    op.add_column('songs', sa.Column('filename', sa.String(), nullable=False))
    op.drop_constraint('songs_file_id_fkey', 'songs', type_='foreignkey')
    op.drop_column('songs', 'file_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('file_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('songs_file_id_fkey', 'songs', 'files', ['file_id'], ['id'])
    op.drop_column('songs', 'filename')
    op.add_column('dances', sa.Column('file_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('dances_file_id_fkey', 'dances', 'files', ['file_id'], ['id'])
    op.drop_column('dances', 'filename')
    # ### end Alembic commands ###
