"""fixed uuids

Revision ID: eefdf54e15a0
Revises: 45d7ae45c60d
Create Date: 2022-05-18 16:34:11.236460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefdf54e15a0'
down_revision = '45d7ae45c60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
